apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
  labels:
    app: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: streamio.azurecr.io/streamio-backend_streaming:latest
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: mongo_uri
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_CLIENT_ID
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_CLIENT_SECRET
          - name: AZURE_TENANT_DOMAIN
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_TENANT_DOMAIN
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_TENANT_ID
          - name: AZURE_MEDIA_SERVICES_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_MEDIA_SERVICES_ACCOUNT_NAME
          - name: AZURE_RESOURCE_GROUP
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_RESOURCE_GROUP
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_SUBSCRIPTION_ID
          - name: AZURE_ARM_TOKEN_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_ARM_TOKEN_AUDIENCE
          - name: AZURE_ARM_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: streaming-secrets
                key: AZURE_ARM_ENDPOINT
          - name: PORT
            value: "4006"
        ports:
        - containerPort: 4006
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  selector:
    app: streaming
  ports:
    - port: 4006
      targetPort: 4006